### ISSUE TITLE
not ready for production?

### ISSUE THREAD

**Issue by wmertens** [johanholmerin/css-to-js.macro#1]
I'm wondering why it says it's not ready for production. I'm investigation style9, not using it yet.

I made a similar thing based on stylis: https://github.com/wmertens/styled-vanilla-extract/blob/main/src/css.ts

**Comment by johanholmerin** [comment]
[The parser](https://github.com/johanholmerin/css-to-js.macro/blob/master/parse-css.js) is just a thrown together hack using [PostCSS JS](https://github.com/postcss/postcss-js). It's very possible that it will generate the wrong output in some situations.
